# Generated by Django 5.2.4 on 2025-07-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkquality',
            name='production_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Volume de Produção (Litros)'),
        ),
    ]
