# Generated by Django 5.2.4 on 2025-07-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('revenue', 'Receita'), ('expense', 'Despesa')], default='expense', max_length=10),
        ),
    ]
