# Generated by Django 5.2.4 on 2025-07-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earring', models.CharField(max_length=20, unique=True, verbose_name='Brinco')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('breed', models.CharField(blank=True, max_length=50, null=True, verbose_name='Raça')),
                ('status', models.CharField(choices=[('lactation', 'Em Lactação'), ('dry', 'Seca'), ('heifer', 'Novilha'), ('calf', 'Bezerra')], default='lactation', max_length=20)),
            ],
        ),
    ]
