# Generated by Django 5.2.4 on 2025-07-04 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herd', '0002_animal_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('vaccination', 'Vacinação'), ('treatment', 'Tratamento'), ('disease', 'Doença')], max_length=30)),
                ('event_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('medication', models.CharField(blank=True, max_length=100, null=True)),
                ('withdrawal_period_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Período de Carência (dias)')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_events', to='herd.animal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento Sanitário',
                'verbose_name_plural': 'Eventos Sanitários',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='ReproductiveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('heat', 'Cio'), ('insemination', 'Inseminação/Cobertura'), ('pregnancy_diagnosis', 'Diagnóstico de Gestação'), ('calving', 'Parto')], max_length=30)),
                ('event_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproductive_events', to='herd.animal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reproductive_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento Reprodutivo',
                'verbose_name_plural': 'Eventos Reprodutivos',
                'ordering': ['-event_date'],
            },
        ),
    ]
